include/env.h: Ensure ulong is defined
To fix these failures when building with musl:
   include/env.h:166:1: error: unknown type name 'ulong'; did you mean 'long'?
ensure that ulong is defined.

Upstream-Status: Pending
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>